name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x # Specify your Deno version
      
      - name: Run Deno fmt check
        run: deno fmt --check
      
      - name: Run Deno lint
        run: deno lint
      
      - name: Run Deno tests
        run: deno test --allow-all
